"""new field info in user model

Revision ID: 8750ff398e40
Revises: 06b2c60f7d12
Create Date: 2020-08-30 17:37:22.088956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8750ff398e40'
down_revision = '06b2c60f7d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    # ### end Alembic commands ###
